const rail=document.getElementById('artist-rail');
const pause=document.getElementById('artist-pause');
const prev=document.getElementById('artist-prev'),next=document.getElementById('artist-next');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let paused=reduced.matches,hover=false,timer,showAll=false;
const allButton=document.getElementById('artist-all');
const pool=Array.from({length:12},(_,i)=>String.fromCharCode(65+i));
let publicProfiles=[...(window.oshilinkPublicProfiles||[])].sort(()=>Math.random()-.5);
function randomSix(){const ids=[...pool];for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];}return ids.slice(0,6);}
let featured=randomSix();
allButton.onclick=()=>{showAll=!showAll;paused=true;render();};
function schedule(){clearInterval(timer);if(!showAll&&!paused&&!hover&&!document.hidden&&rail.scrollWidth>rail.clientWidth+1)timer=setInterval(()=>move(1,false),3500);}
function move(direction,manual=true){if(manual){paused=true;label();}const step=rail.firstElementChild?.getBoundingClientRect().width+parseFloat(getComputedStyle(rail).gap)||178;const max=rail.scrollWidth-rail.clientWidth;const position=rail.scrollLeft;const target=direction>0?(position>=max-5?0:Math.min(position+step,max)):(position<=5?max:Math.max(0,position-step));rail.scrollTo({left:target,behavior:reduced.matches?'instant':'smooth'});schedule();}
function label(){pause.textContent=paused?'自動再生':'一時停止';}
function render(){rail.replaceChildren();const demo=document.getElementById('demo').checked;const source=demo?(showAll?pool:featured):(showAll?publicProfiles:publicProfiles.slice(0,6));source.forEach((item,i)=>{const id=demo?item:item.id,nameText=demo?`歌い手 ${id}`:item.display_name;const a=document.createElement('a');a.href=demo?`./profile.html?artist=${id}`:`./profile.html?id=${encodeURIComponent(id)}`;a.className='artist-link';a.setAttribute('aria-label',demo?`${nameText}のプロフィール（架空のサンプル）`:`${nameText}のプロフィール`);const icon=document.createElement('span');icon.className='artist-icon';icon.style.setProperty('--artist-color',['#623651','#314e6c','#535178','#536949','#774c3a','#54436c'][i%6]);icon.setAttribute('aria-hidden','true');icon.textContent=demo?id:nameText.slice(0,1);const name=document.createElement('strong');name.textContent=nameText;const note=document.createElement('small');note.textContent=demo?'表示サンプル':item.region||'プロフィール公開中';a.append(icon,name,note);rail.append(a);});if(!source.length){const p=document.createElement('p');p.textContent='歌い手はまだ掲載されていません。';rail.append(p);}prev.disabled=next.disabled=pause.disabled=source.length<2||showAll;allButton.hidden=source.length<=6;allButton.textContent=showAll?'紹介スライドに戻る':'すべての歌い手を見る ↗';allButton.setAttribute('aria-expanded',String(showAll));rail.style.flexWrap=showAll?'wrap':'nowrap';document.getElementById('artist-description').textContent=!source.length?'公開プロフィールが登録されると、こちらに表示されます。':showAll?(demo?'歌い手一覧（架空のサンプル12人）':'公開中の歌い手一覧'):'※ランダムに最大6人紹介しています。';rail.scrollLeft=0;label();schedule();}
prev.onclick=()=>move(-1);next.onclick=()=>move(1);pause.onclick=()=>{paused=!paused;label();schedule();};rail.addEventListener('mouseenter',()=>{hover=true;schedule();});rail.addEventListener('mouseleave',()=>{hover=false;schedule();});rail.addEventListener('focusin',()=>{paused=true;label();schedule();});rail.addEventListener('pointerdown',()=>{paused=true;label();schedule();});document.addEventListener('visibilitychange',schedule);window.addEventListener('resize',schedule);reduced.addEventListener('change',()=>{paused=reduced.matches;label();schedule();});document.getElementById('demo').addEventListener('change',render);render();
window.addEventListener('oshilink:artists',event=>{publicProfiles=[...(event.detail||[])].sort(()=>Math.random()-.5);showAll=false;render();});
